#!/bin/bash

# 定义变量
HOST="www.baidu.com"
PING_COUNT=5

# 尝试通过IPv4 ping
if ping -c $PING_COUNT $HOST > /dev/null 2>&1; then
    echo "IPv4 ok."
else
    echo "IPv4 not ok."
    exit 1
fi

# 如果IPv4 ping成功，接着尝试通过IPv6 ping
if ping6 -c $PING_COUNT $HOST > /dev/null 2>&1; then
    echo "IPv6 ok."
else
    echo "IPv6 not ok."
    echo "restart wan_6 ..."
    ifup wan_6
    echo "restart wan_6 done"
fi